/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: VMware vFabric tc Runtime 2.6.4.RELEASE/7.0.25.B.RELEASE
 * Generated at: 2012-03-23 23:18:59 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.controllers.resources;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class resource_002dhealthtrend_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

private static org.apache.jasper.runtime.ProtectedFunctionMapper _jspx_fnmap_0;
private static org.apache.jasper.runtime.ProtectedFunctionMapper _jspx_fnmap_1;

static {
  _jspx_fnmap_0= org.apache.jasper.runtime.ProtectedFunctionMapper.getMapForFunction("insight:escapeJs", org.springframework.web.util.JavaScriptUtils.class, "javaScriptEscape", new Class[] {java.lang.String.class});
  _jspx_fnmap_1= org.apache.jasper.runtime.ProtectedFunctionMapper.getInstance();
  _jspx_fnmap_1.mapFunction("fn:escapeXml", org.apache.taglibs.standard.functions.Functions.class, "escapeXml", new Class[] {java.lang.String.class});
  _jspx_fnmap_1.mapFunction("insight:escapeJs", org.springframework.web.util.JavaScriptUtils.class, "javaScriptEscape", new Class[] {java.lang.String.class});
}

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/WEB-INF/insight.tld", Long.valueOf(1309827226000L));
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ffmt_005fsetTimeZone_0026_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fspring_005fmessage_0026_005fvar_005fcode_005fnobody;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005ffmt_005fsetTimeZone_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fspring_005fmessage_0026_005fvar_005fcode_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005ffmt_005fsetTimeZone_0026_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fspring_005fmessage_0026_005fvar_005fcode_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, false, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write('\n');
      out.write('\n');
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write('\n');
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f0.setParent(null);
    // /WEB-INF/controllers/resources/resource-healthtrend.jsp(10,0) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty timeZone}", java.lang.Boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false)).booleanValue());
    int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
    if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write('\n');
        out.write('	');
        if (_jspx_meth_fmt_005fsetTimeZone_005f0(_jspx_th_c_005fif_005f0, _jspx_page_context))
          return true;
        out.write('\n');
        int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
    return false;
  }

  private boolean _jspx_meth_fmt_005fsetTimeZone_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:setTimeZone
    org.apache.taglibs.standard.tag.rt.fmt.SetTimeZoneTag _jspx_th_fmt_005fsetTimeZone_005f0 = (org.apache.taglibs.standard.tag.rt.fmt.SetTimeZoneTag) _005fjspx_005ftagPool_005ffmt_005fsetTimeZone_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.SetTimeZoneTag.class);
    _jspx_th_fmt_005fsetTimeZone_005f0.setPageContext(_jspx_page_context);
    _jspx_th_fmt_005fsetTimeZone_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f0);
    // /WEB-INF/controllers/resources/resource-healthtrend.jsp(11,1) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_fmt_005fsetTimeZone_005f0.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${timeZone}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
    int _jspx_eval_fmt_005fsetTimeZone_005f0 = _jspx_th_fmt_005fsetTimeZone_005f0.doStartTag();
    if (_jspx_th_fmt_005fsetTimeZone_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005ffmt_005fsetTimeZone_0026_005fvalue_005fnobody.reuse(_jspx_th_fmt_005fsetTimeZone_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005ffmt_005fsetTimeZone_0026_005fvalue_005fnobody.reuse(_jspx_th_fmt_005fsetTimeZone_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f1.setParent(null);
    // /WEB-INF/controllers/resources/resource-healthtrend.jsp(14,0) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not resource.resource.type.responseTimeAware}", java.lang.Boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false)).booleanValue());
    int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
    if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\n");
        out.write("\t<div class=\"submodule\">\n");
        out.write("\t\t<h2 style=\"float: left;\">Health Trend</h2>\n");
        out.write("\t\t<div id=\"healthTrend\" style=\"height: 150px; clear: both\"></div>\n");
        out.write("\t\t<script type=\"text/javascript\">\n");
        out.write("\t\t\tdojo.addOnLoad(function() {\n");
        out.write("\t\t\t\tdojo.require(\"insight.charting.MultiResourceChart\");\n");
        out.write("\t\t\t\tdojo.require(\"insight.charting._HealthBands\");\n");
        out.write("\t\t\t\tdojo.require(\"insight.charting.axis2d.Fixed\");\n");
        out.write("\t\t\t\tdojo.require(\"insight.charting.plot2d.HeatColumns\");\n");
        out.write("\t\t\t\tdojo.require(\"insight.charting.plot2d.HorizontalBands\");\n");
        out.write("\t\t\t\tdojo.require(\"insight.charting.themes.Spring\");\n");
        out.write("\t\t\t\tdojo.require(\"insight.resources.ResourceKey\");\n");
        out.write("\t\t\t\tdojo.require(\"dijit.form.Button\");\n");
        out.write("\t\t\t\tvar timeRange = Insight.getTimeRange();\n");
        out.write("\t\t\t\tvar requstedResource = new insight.resources.ResourceKey('");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${insight:escapeJs(resourceKey)}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, _jspx_fnmap_0, false));
        out.write("'), resource;\n");
        out.write("\t\t\t\tif (\"Server\" === requstedResource.getType()) {\n");
        out.write("\t\t\t\t\tresource = requstedResource.makeQueryKey(\"Application.Server\");\n");
        out.write("\t\t\t\t}\n");
        out.write("\t\t\t\telse if (requstedResource.getAttribute(\"Server\")) {\n");
        out.write("\t\t\t\t\tresource = requstedResource.makeQueryKey(\"Application.Server.EndPoint\");\n");
        out.write("\t\t\t\t}\n");
        out.write("\t\t\t\telse {\n");
        out.write("\t\t\t\t\tresource = requstedResource.makeQueryKey(\"Application.EndPoint\");\n");
        out.write("\t\t\t\t}\n");
        out.write("\t\t\t\tvar healthBands = insight.charting._HealthBands.healthBands;\n");
        out.write("\t\t\t\tvar chart = new insight.charting.MultiResourceChart({\n");
        out.write("\t\t\t\t\ttimeRange: timeRange,\n");
        out.write("\t\t\t\t\tdataPoints: 30,\n");
        out.write("\t\t\t\t\ttype: dojox.charting.plot2d.Lines,\n");
        out.write("\t\t\t\t\ttheme: insight.charting.themes.SpringTransparent,\n");
        out.write("\t\t\t\t\turl: Insight.buildUri(\"/services/resources/{resource}/{start}/{end}/health\", {\n");
        out.write("\t\t\t\t\t\tresource: resource.toString(),\n");
        out.write("\t\t\t\t\t\tstart: timeRange.getStart(),\n");
        out.write("\t\t\t\t\t\tend: timeRange.getEnd()\n");
        out.write("\t\t\t\t\t}),\n");
        out.write("\t\t\t\t\tyAxisArgs: { type: insight.charting.axis2d.Fixed, vertical: true, min: -0.1, max: 1.1, labels: healthBands, labelFunc: \"_healthLabelFunc\" },\n");
        out.write("\t\t\t\t\tgridHLines: false,\n");
        out.write("\t\t\t\t\tscaleOnRestack: false\n");
        out.write("\t\t\t\t}, \"healthTrend\");\n");
        out.write("\t\t\t\tchart.addStore(\"metrics\", Insight.buildUri(\"/services/resources/{resource}/{start}/{end}/metricData\", {\n");
        out.write("\t\t\t\t\tresource: '");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${insight:escapeJs(resourceKey)}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, _jspx_fnmap_0, false));
        out.write("',\n");
        out.write("\t\t\t\t\tstart: timeRange.getStart(),\n");
        out.write("\t\t\t\t\tend: timeRange.getEnd()\n");
        out.write("\t\t\t\t}));\n");
        out.write("\t\t\t\tchart.addResourceMetricPlot(\"metrics\", \"errorRate\", \"Error Rate\",\n");
        out.write("\t\t\t\t\t{ hidden: true, includeZero: true, max: 1, fixed: false, minorTicks: false, labelFunc: function(t, n, p) { return chart._errorRateLabelFunc(t, n, p, chart._names(\"errorRate\").axis) } },\n");
        out.write("\t\t\t\t\t{ type: insight.charting.plot2d.HeatColumns },\n");
        out.write("\t\t\t\t\t{ fill: new dojo.Color([0xCC, 0x33, 0x33, 0.5]) }\n");
        out.write("\t\t\t\t);\n");
        out.write("\t\t\t\tchart.chart.addPlot(\"healthBands\", { type: insight.charting.plot2d.HorizontalBands, bands: healthBands });\n");
        out.write("\t\t\t\tchart.subscribe(\"Insight.highlightResource\", chart.highlightResource);\n");
        out.write("\t\t\t\tchart.subscribe(\"Insight.blurResource\", chart.blurResource);\n");
        out.write("\t\t\t\tchart.subscribe(\"Insight.restackResource\", function(resource) { chart.restackResource(resource, \"main\"); });\n");
        out.write("\t\t\t\tchart.subscribe(\"Insight.timeRangePulse\", function(timeRange) {\n");
        out.write("\t\t\t\t\tthis.updateTimeRange({ timeRange: timeRange });\n");
        out.write("\t\t\t\t});\n");
        out.write("\t\t\t\tchart.startup();\n");
        out.write("\t\t\t\tchart.chart.movePlotToBack(\"healthBands\");\n");
        out.write("\t\t\t\t");
        if (_jspx_meth_c_005fif_005f2(_jspx_th_c_005fif_005f1, _jspx_page_context))
          return true;
        out.write("\n");
        out.write("\t\t\t});\n");
        out.write("\t\t</script>\n");
        out.write("\t</div>\n");
        int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f2 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f2.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f1);
    // /WEB-INF/controllers/resources/resource-healthtrend.jsp(73,4) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f2.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not devEdition and resourceType.typeName eq 'Application'}", java.lang.Boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false)).booleanValue());
    int _jspx_eval_c_005fif_005f2 = _jspx_th_c_005fif_005f2.doStartTag();
    if (_jspx_eval_c_005fif_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\n");
        out.write("\t\t\t\t\tvar controls, control, serversToggle, endPointsToggle;\n");
        out.write("\t\t\t\t\tcontrols = dojo.create(\"ul\", { className: \"controls\" }, chart.domNode, \"before\");\n");
        out.write("\t\t\t\t\tcontrol = dojo.create(\"li\", { className: \"control\" }, controls);\n");
        out.write("\t\t\t\t\t");
        if (_jspx_meth_spring_005fmessage_005f0(_jspx_th_c_005fif_005f2, _jspx_page_context))
          return true;
        out.write("\n");
        out.write("\t\t\t\t\tendPointsToggle = new dijit.form.Button({ label: \"");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${fn:escapeXml(insight:escapeJs(label))}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, _jspx_fnmap_1, false));
        out.write("\" });\n");
        out.write("\t\t\t\t\t");
        if (_jspx_meth_spring_005fmessage_005f1(_jspx_th_c_005fif_005f2, _jspx_page_context))
          return true;
        out.write("\n");
        out.write("\t\t\t\t\tserversToggle = new dijit.form.Button({ label: \"");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${fn:escapeXml(insight:escapeJs(label))}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, _jspx_fnmap_1, false));
        out.write("\" });\n");
        out.write("\t\t\t\t\tendPointsToggle.connect(endPointsToggle, \"onClick\", function() {\n");
        out.write("\t\t\t\t\t\tchart.urlParam('resource', requstedResource.makeQueryKey('Application.EndPoint'), 'main');\n");
        out.write("\t\t\t\t\t\tchart.reset();\n");
        out.write("\t\t\t\t\t\tdojo.addClass(endPointsToggle.domNode, \"dijitHighlight\");\n");
        out.write("\t\t\t\t\t\tdojo.removeClass(serversToggle.domNode, \"dijitHighlight\");\n");
        out.write("\t\t\t\t\t});\n");
        out.write("\t\t\t\t\tserversToggle.connect(serversToggle, \"onClick\", function() {\n");
        out.write("\t\t\t\t\t\tchart.urlParam('resource', requstedResource.makeQueryKey('Application.Server'), 'main');\n");
        out.write("\t\t\t\t\t\tchart.reset();\n");
        out.write("\t\t\t\t\t\tdojo.addClass(serversToggle.domNode, \"dijitHighlight\");\n");
        out.write("\t\t\t\t\t\tdojo.removeClass(endPointsToggle.domNode, \"dijitHighlight\");\n");
        out.write("\t\t\t\t\t});\n");
        out.write("\t\t\t\t\tdojo.addClass(endPointsToggle.domNode, \"dijitHighlight\");\n");
        out.write("\t\t\t\t\tdojo.place(endPointsToggle.domNode, control);\n");
        out.write("\t\t\t\t\tdojo.place(serversToggle.domNode, control);\n");
        out.write("\t\t\t\t\tendPointsToggle.startup();\n");
        out.write("\t\t\t\t\tserversToggle.startup();\n");
        out.write("\t\t\t\t");
        int evalDoAfterBody = _jspx_th_c_005fif_005f2.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f2);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f2);
    return false;
  }

  private boolean _jspx_meth_spring_005fmessage_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f2, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  spring:message
    org.springframework.web.servlet.tags.MessageTag _jspx_th_spring_005fmessage_005f0 = (org.springframework.web.servlet.tags.MessageTag) _005fjspx_005ftagPool_005fspring_005fmessage_0026_005fvar_005fcode_005fnobody.get(org.springframework.web.servlet.tags.MessageTag.class);
    _jspx_th_spring_005fmessage_005f0.setPageContext(_jspx_page_context);
    _jspx_th_spring_005fmessage_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f2);
    // /WEB-INF/controllers/resources/resource-healthtrend.jsp(77,5) name = code type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_spring_005fmessage_005f0.setCode("repo.resources.types.APPLICATION_END_POINT.context.APPLICATION.name.pural");
    // /WEB-INF/controllers/resources/resource-healthtrend.jsp(77,5) name = var type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_spring_005fmessage_005f0.setVar("label");
    int[] _jspx_push_body_count_spring_005fmessage_005f0 = new int[] { 0 };
    try {
      int _jspx_eval_spring_005fmessage_005f0 = _jspx_th_spring_005fmessage_005f0.doStartTag();
      if (_jspx_th_spring_005fmessage_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_spring_005fmessage_005f0[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_spring_005fmessage_005f0.doCatch(_jspx_exception);
    } finally {
      _jspx_th_spring_005fmessage_005f0.doFinally();
      _005fjspx_005ftagPool_005fspring_005fmessage_0026_005fvar_005fcode_005fnobody.reuse(_jspx_th_spring_005fmessage_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_spring_005fmessage_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f2, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  spring:message
    org.springframework.web.servlet.tags.MessageTag _jspx_th_spring_005fmessage_005f1 = (org.springframework.web.servlet.tags.MessageTag) _005fjspx_005ftagPool_005fspring_005fmessage_0026_005fvar_005fcode_005fnobody.get(org.springframework.web.servlet.tags.MessageTag.class);
    _jspx_th_spring_005fmessage_005f1.setPageContext(_jspx_page_context);
    _jspx_th_spring_005fmessage_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f2);
    // /WEB-INF/controllers/resources/resource-healthtrend.jsp(79,5) name = code type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_spring_005fmessage_005f1.setCode("repo.resources.types.APPLICATION_SERVER.context.APPLICATION.name.pural");
    // /WEB-INF/controllers/resources/resource-healthtrend.jsp(79,5) name = var type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_spring_005fmessage_005f1.setVar("label");
    int[] _jspx_push_body_count_spring_005fmessage_005f1 = new int[] { 0 };
    try {
      int _jspx_eval_spring_005fmessage_005f1 = _jspx_th_spring_005fmessage_005f1.doStartTag();
      if (_jspx_th_spring_005fmessage_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_spring_005fmessage_005f1[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_spring_005fmessage_005f1.doCatch(_jspx_exception);
    } finally {
      _jspx_th_spring_005fmessage_005f1.doFinally();
      _005fjspx_005ftagPool_005fspring_005fmessage_0026_005fvar_005fcode_005fnobody.reuse(_jspx_th_spring_005fmessage_005f1);
    }
    return false;
  }
}
