/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: VMware vFabric tc Runtime 2.6.4.RELEASE/7.0.25.B.RELEASE
 * Generated at: 2012-03-23 23:19:01 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.controllers.resources;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class resource_002dcombochart_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

private static org.apache.jasper.runtime.ProtectedFunctionMapper _jspx_fnmap_0;

static {
  _jspx_fnmap_0= org.apache.jasper.runtime.ProtectedFunctionMapper.getMapForFunction("insight:escapeJs", org.springframework.web.util.JavaScriptUtils.class, "javaScriptEscape", new Class[] {java.lang.String.class});
}

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/WEB-INF/insight.tld", Long.valueOf(1309827226000L));
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ffmt_005fsetTimeZone_0026_005fvalue_005fnobody;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005ffmt_005fsetTimeZone_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005ffmt_005fsetTimeZone_0026_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, false, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write('\n');
      out.write('\n');
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write('\n');
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f0.setParent(null);
    // /WEB-INF/controllers/resources/resource-combochart.jsp(10,0) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty timeZone}", java.lang.Boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false)).booleanValue());
    int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
    if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write('\n');
        out.write('	');
        if (_jspx_meth_fmt_005fsetTimeZone_005f0(_jspx_th_c_005fif_005f0, _jspx_page_context))
          return true;
        out.write('\n');
        int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
    return false;
  }

  private boolean _jspx_meth_fmt_005fsetTimeZone_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:setTimeZone
    org.apache.taglibs.standard.tag.rt.fmt.SetTimeZoneTag _jspx_th_fmt_005fsetTimeZone_005f0 = (org.apache.taglibs.standard.tag.rt.fmt.SetTimeZoneTag) _005fjspx_005ftagPool_005ffmt_005fsetTimeZone_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.SetTimeZoneTag.class);
    _jspx_th_fmt_005fsetTimeZone_005f0.setPageContext(_jspx_page_context);
    _jspx_th_fmt_005fsetTimeZone_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f0);
    // /WEB-INF/controllers/resources/resource-combochart.jsp(11,1) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_fmt_005fsetTimeZone_005f0.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${timeZone}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
    int _jspx_eval_fmt_005fsetTimeZone_005f0 = _jspx_th_fmt_005fsetTimeZone_005f0.doStartTag();
    if (_jspx_th_fmt_005fsetTimeZone_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005ffmt_005fsetTimeZone_0026_005fvalue_005fnobody.reuse(_jspx_th_fmt_005fsetTimeZone_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005ffmt_005fsetTimeZone_0026_005fvalue_005fnobody.reuse(_jspx_th_fmt_005fsetTimeZone_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f1.setParent(null);
    // /WEB-INF/controllers/resources/resource-combochart.jsp(14,0) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${resource.resource.type.responseTimeAware}", java.lang.Boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false)).booleanValue());
    int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
    if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\n");
        out.write("\t<div id=\"comboChart\" style=\"height: 150px; clear: both\"></div>\n");
        out.write("\t<div id=\"comboHealthChart\" style=\"height: 65px; clear: both\"></div>\n");
        out.write("\t<script type=\"text/javascript\">\n");
        out.write("\t\tdojo.addOnLoad(function() {\n");
        out.write("\t\t\tdojo.require(\"dojox.charting.plot2d.Areas\");\n");
        out.write("\t\t\tdojo.require(\"dojox.charting.plot2d.Lines\");\n");
        out.write("\t\t\tdojo.require(\"insight.charting.MultiMetricResourceChart\");\n");
        out.write("\t\t\tdojo.require(\"insight.charting.MultiResourceChart\");\n");
        out.write("\t\t\tdojo.require(\"insight.charting._HealthBands\");\n");
        out.write("\t\t\tdojo.require(\"insight.charting.action2d.StrokeHighlight\");\n");
        out.write("\t\t\tdojo.require(\"insight.charting.axis2d.Fixed\");\n");
        out.write("\t\t\tdojo.require(\"insight.charting.axis2d.Legend\");\n");
        out.write("\t\t\tdojo.require(\"insight.charting.plot2d.HeatColumns\");\n");
        out.write("\t\t\tdojo.require(\"insight.charting.plot2d.HorizontalBands\");\n");
        out.write("\t\t\tvar timeRange = Insight.getTimeRange()\n");
        out.write("\t\t\tvar dataPoints = dojo.isIE ? 30 : 60;\n");
        out.write("\t\t\tvar chart = new insight.charting.MultiMetricResourceChart({\n");
        out.write("\t\t\t\tclickable: true,\n");
        out.write("\t\t\t\ttimeRange: timeRange,\n");
        out.write("\t\t\t\tdataPoints: dataPoints,\n");
        out.write("\t\t\t\turl: Insight.buildUri(\"/services/resources/{resource}/{start}/{end}/metricData\", {\n");
        out.write("\t\t\t\t\tresource: '");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${insight:escapeJs(resource.resource.key)}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, _jspx_fnmap_0, false));
        out.write("',\n");
        out.write("\t\t\t\t\tstart: timeRange.getStart(),\n");
        out.write("\t\t\t\t\tend: timeRange.getEnd()\n");
        out.write("\t\t\t\t}),\n");
        out.write("\t\t\t\thideXAxis: true,\n");
        out.write("\t\t\t\tmargins: {l: 10, t: 10, r: 10, b: 0}\n");
        out.write("\t\t\t}, \"comboChart\");\n");
        out.write("\t\t\tchart.addResourceMetricPlot(\"main\", \"throughput\", \"Throughput Trend\",\n");
        out.write("\t\t\t\t{ maxLabelSize: 57, includeZero: true, fixed: false, minorTicks: false, labelFunc: function(t, n, p) { return chart._throughputLabelFunc(t, n, p, chart._names(\"throughput\").axis) } },\n");
        out.write("\t\t\t\t{ type: dojox.charting.plot2d.Areas, markers: true, tension: \"S\" },\n");
        out.write("\t\t\t\t{ fill: new dojo.Color([0xFF, 0xD1, 0x19, 0.5]), stroke: { color: \"#FFFFFF\", width: 2 }, markerFill: new dojo.Color([0xFF, 0xFF, 0xFF, 0]), markerStroke: { color: new dojo.Color([0xFF, 0xFF, 0xFF, 0]) } }\n");
        out.write("\t\t\t);\n");
        out.write("\t\t\tchart.addResourceMetricPlotAction(\"throughput\", insight.charting.action2d.StrokeHighlight, { highlight: \"#2354A4\" })\n");
        out.write("\t\t\tchart.addResourceMetricPlot(\"main\", \"responseTime\", \"Response Time Trend\",\n");
        out.write("\t\t\t\t{ maxLabelSize: 57, includeZero: true, fixed: false, minorTicks: false, labelFunc: function(t, n, p) { return chart._responseTimeLabelFunc(t, n, p, chart._names(\"responseTime\").axis) } },\n");
        out.write("\t\t\t\t{ type: dojox.charting.plot2d.Lines, markers: true, tension: \"S\" },\n");
        out.write("\t\t\t\t{ stroke: { color:\"#005AFF\", width: 1.5 }, markerStroke: { color: new dojo.Color([0x00, 0x5A, 0xFF, 0]) } }\n");
        out.write("\t\t\t);\n");
        out.write("\t\t\tchart.addResourceMetricPlotAction(\"responseTime\", insight.charting.action2d.StrokeHighlight, { highlight: \"#2354A4\" })\n");
        out.write("\t\t\tchart.addResourceMetricPlot(\"main\", \"errorRate\", \"Error Rate\",\n");
        out.write("\t\t\t\t{ maxLabelSize: 57, includeZero: true, max: 1, fixed: false, minorTicks: false, labelFunc: function(t, n, p) { return chart._errorRateLabelFunc(t, n, p, chart._names(\"errorRate\").axis) } },\n");
        out.write("\t\t\t\t{ type: insight.charting.plot2d.HeatColumns },\n");
        out.write("\t\t\t\t{ fill: new dojo.Color([0xCC, 0x33, 0x33, 0.5]) }\n");
        out.write("\t\t\t);\n");
        out.write("\t\t\tchart.chart.addAxis(\"legend\", { type: insight.charting.axis2d.Legend, series: [chart._names(\"throughput\").series, chart._names(\"errorRate\").series, chart._names(\"responseTime\").series ], leftBottom: false });\n");
        out.write("\t\t\tchart.chart.movePlotToBack(chart._names(\"errorRate\").plot);\n");
        out.write("\t\t\tchart.chart.movePlotToBack(chart._names(\"throughput\").plot);\n");
        out.write("\t\t\tchart.chart.movePlotToBack(chart._names(\"grid\").plot);\n");
        out.write("\t\t\tchart.connect(chart, \"onChartElementClick\", function(e){\n");
        out.write("\t\t\t\tif (e.plot.name == \"foregroundColumnsPlot\") {\n");
        out.write("\t\t\t\t\tvar range = e.run.data[e.index];\n");
        out.write("\t\t\t\t\tInsight.loadWindow(range.start, range.end, '");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${insight:escapeJs(resource.resource.key)}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, _jspx_fnmap_0, false));
        out.write("');\n");
        out.write("\t\t\t\t}\n");
        out.write("\t\t\t});\n");
        out.write("\t\t\tchart.subscribe(\"Insight.timeRangePulse\", function(timeRange) {\n");
        out.write("\t\t\t\tthis.updateTimeRange({ timeRange: timeRange });\n");
        out.write("\t\t\t});\n");
        out.write("\t\t\tvar healthBands = insight.charting._HealthBands.healthBands;\n");
        out.write("\t\t\tvar healthChart = new insight.charting.MultiMetricResourceChart({\n");
        out.write("\t\t\t\ttimeRange: timeRange,\n");
        out.write("\t\t\t\tdataPoints: dataPoints,\n");
        out.write("\t\t\t\ttype: dojox.charting.plot2d.Lines,\n");
        out.write("\t\t\t\ttheme: insight.charting.themes.SpringTransparent,\n");
        out.write("\t\t\t\turl: Insight.buildUri(\"/services/resources/{resource}/{start}/{end}/metricData\", {\n");
        out.write("\t\t\t\t\tresource: '");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${insight:escapeJs(resource.resource.key)}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, _jspx_fnmap_0, false));
        out.write("',\n");
        out.write("\t\t\t\t\tstart: timeRange.getStart(),\n");
        out.write("\t\t\t\t\tend: timeRange.getEnd()\n");
        out.write("\t\t\t\t}),\n");
        out.write("\t\t\t\tgridHLines: false,\n");
        out.write("\t\t\t\tscaleOnRestack: false,\n");
        out.write("\t\t\t\tmargins: {l: 70, t: 0, r: 70, b: 10}\n");
        out.write("\t\t\t}, \"comboHealthChart\");\n");
        out.write("\t\t\thealthChart.addResourceMetricPlot(\"main\", \"health\", \"Health\",\n");
        out.write("\t\t\t\t{ type: dojox.charting.axis2d.Invisible, vertical: true, min: -0.1, max: 1.1, labelFunc: healthChart._healthLabelFunc },\n");
        out.write("\t\t\t\t{ type: dojox.charting.plot2d.Lines, markers: true, tension: \"S\" },\n");
        out.write("\t\t\t\t{ stroke: { color: \"#339933\", width: 1.5 }, markerFill: new dojo.Color([0x33, 0x99, 0x33, 0]), markerStroke: { color: new dojo.Color([0x33, 0x99, 0x33, 0]) } }\n");
        out.write("\t\t\t);\n");
        out.write("\t\t\thealthChart.addResourceMetricPlotAction(\"health\", insight.charting.action2d.StrokeHighlight, { highlight: \"#2354A4\" })\n");
        out.write("\t\t\thealthChart.chart.addPlot(\"healthBands\", { type: insight.charting.plot2d.HorizontalBands, bands: healthBands, vAxis: healthChart._names(\"health\").axis });\n");
        out.write("\t\t\thealthChart.subscribe(\"Insight.timeRangePulse\", function(timeRange) {\n");
        out.write("\t\t\t\tthis.updateTimeRange({ timeRange: timeRange });\n");
        out.write("\t\t\t});\n");
        out.write("\t\t\tchart.startup();\n");
        out.write("\t\t\thealthChart.startup();\n");
        out.write("\t\t\tchart.chart.axes[\"legend\"].dirty = true;\n");
        out.write("\t\t\thealthChart.chart.movePlotToBack(\"healthBands\");\n");
        out.write("\t\t});\n");
        out.write("\t</script>\n");
        int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
    return false;
  }
}
